name: expense 
networks:
  default:
    name: expense
volumes:
  mysql:
   #external: true
services:
  mysql:
    image: mysql:v1.0 # this one equivalent to the -t 
    container_name: mysql # --name
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MYSQL_USER=expense
      - MYSQL_PASSWORD=ExpenseApp@1
      - MYSQL_DATABASE=transactions
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume
  backend:
    image: backend:v1.0
    container_name: backend
    cmd: ["sleep","10"]
    depends_on: 
    - mysql
  frontend:
    image: frontend:v1.0
    container_name: frontend
    depends_on:
      - backend
    ports:
     - "80:80"


