FROM node:20.15.0-alpine3.20
ENV DB_HOST=mysql
RUN adduser expense 
RUN mkdir /opt/server
RUN chown expense:expense /opt/server
WORKDIR /opt/server
COPY package.json .
COPY *.js /opt/server
RUN npm install 
USER expense 
EXPOSE 8081
CMD [ "node","index.js" ]


